// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQBtz8gq3INd2Pu16ket6X7jIXLUU0COw',
    appId: '1:244757041059:web:5a89c8fbdf78aa4ba45416',
    messagingSenderId: '244757041059',
    projectId: 'petcarerecord',
    authDomain: 'petcarerecord.firebaseapp.com',
    storageBucket: 'petcarerecord.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB39vZWsbeJmSJHo1N4ltqBFFXFroA_Uoc',
    appId: '1:244757041059:android:db4f89e99b812cada45416',
    messagingSenderId: '244757041059',
    projectId: 'petcarerecord',
    storageBucket: 'petcarerecord.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtwnw9gJ7RXKYJ3Csr7m8EW38MyYzw_R8',
    appId: '1:244757041059:ios:672a9332010969f0a45416',
    messagingSenderId: '244757041059',
    projectId: 'petcarerecord',
    storageBucket: 'petcarerecord.appspot.com',
    iosClientId: '244757041059-n5cip7e39hvttnbnig4p3j33p5ppudt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcareRecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtwnw9gJ7RXKYJ3Csr7m8EW38MyYzw_R8',
    appId: '1:244757041059:ios:ce1733ad7f078435a45416',
    messagingSenderId: '244757041059',
    projectId: 'petcarerecord',
    storageBucket: 'petcarerecord.appspot.com',
    iosClientId: '244757041059-1dsnk9738kouq12c5bp44pm6r3uadks5.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcareRecord.RunnerTests',
  );
}
